spring:
  application:
    name: Gateway
  cloud:
    gateway:
      routes:
        - id: USERSERVICE
          uri: lb://USERSERVICE
          predicates:
            - Path=/users/**
        - id: EVENTSERVICE
          uri: lb://EVENTSERVICE
          predicates:
            - Path=/event/**
        - id: RATINGSERVICE
          uri: lb://RATINGSERVICE
          predicates:
            - Path=/rating/**
  mail:
    host: smtp.gmail.com
    port: 587
    username: manitej03@gmail.com
    password: qelbckcbgmvpdyqu
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
logging:
  level:
    com.netflix.discovery: DEBUG
    org.springframework.cloud.netflix.eureka: DEBUG

server:
  port: 9095

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9093/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
